### ISSUE TITLE
Error while translating, no problem without html tags

### ISSUE THREAD

**Issue by dingedi** [argosopentech/translate-html#6]
I just spotted something, for the translation of the word Talla (ES) to FR (for example) there are no problems without html tags, but with it does not work.

[https://libretranslate.com/?source=es&target=fr&q=Talla (OK)](https://libretranslate.com/?source=es&target=fr&q=Talla)
[https://libretranslate.com/?source=es&target=fr&q=%253Cdiv%253ETalla%253C%2Fdiv%253E (BAD)](https://libretranslate.com/?source=es&target=fr&q=%253Cdiv%253ETalla%253C%2Fdiv%253E)

do you think the problem comes from argos or from translate-html? @PJ-Finlay

**Comment by PJ-Finlay** [comment]
It looks like both Argos Translate and translate-html translate "Talla" from Spanish to English as "Talla" so this isn't a problem with translate-html. Translating single words has been a consistent weakness for Argos Translate which is why I've been trying to use Wiktionary data to include more single word translations in the training data.

What's strange is that LibreTranslate translates correctly. My best guess is that this is caused by transliteration or something similar because a small change could lead to a correct translation. For example, Argos Translate translates "talla" as "size".

```
(env) $ export DEBUG=1
(env) $ python examples/translatehtmlexample.py 
DEBUG:root:('get_installed_languages',)
DEBUG:root:('paragraphs:', ['Talla'])
DEBUG:root:('apply_packaged_translation', 'Talla')
DEBUG:root:('sentences', ['Talla'])
DEBUG:root:('tokenized', [['▁Tal', 'la']])
DEBUG:root:('translated_batches', [TranslationResult(hypotheses=[['▁Tal', 'la']], scores=[-1.1473311185836792], attention=[])])
DEBUG:root:('value_hypotheses:', [('Talla', -1.1473311185836792)])
DEBUG:root:('translated_paragraphs:', [[('Talla', -1.1473311185836792)]])
DEBUG:root:('hypotheses_to_return:', [('Talla', -1.1473311185836792)])
<div>Talla</div>
(env) $ argos-translate -f es -t en "Talla "
DEBUG:root:('get_installed_languages',)
DEBUG:root:('paragraphs:', ['Talla '])
DEBUG:root:('apply_packaged_translation', 'Talla ')
DEBUG:root:('sentences', ['Talla'])
DEBUG:root:('tokenized', [['▁Tal', 'la']])
DEBUG:root:('translated_batches', [TranslationResult(hypotheses=[['▁Tal', 'la']], scores=[-1.1473311185836792], attention=[])])
DEBUG:root:('value_hypotheses:', [('Talla', -1.1473311185836792)])
DEBUG:root:('translated_paragraphs:', [[('Talla', -1.1473311185836792)]])
DEBUG:root:('hypotheses_to_return:', [('Talla', -1.1473311185836792)])
Talla
```
